version: '3.8'
services:
  postgres:
    image: "postgres:16"
    env_file:
      - .env
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:5432'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PGADMIN_PORT}:80"
  redis:
    image: "redis:6"
    ports:
      - "127.0.0.1:${REDIS_PORT}:${INTERNAL_REDIS_PORT}"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:${INTERNAL_REDIS_PORT}
    ports:
    - "127.0.0.1:8081:8081"
    depends_on:
      - redis